### ISSUE TITLE
Run Projects Locally

### ISSUE THREAD

**Issue by husamettinarabaci** [octoposprime/op-be-docs#3]
Everyone should run all projects locally. Please comment on this issue after perfectly running.

**Comment by Smnrgcl** [comment]
I successfully ran the project locally. However, I had to make the following changes while running the project:

1. Since the 'make' command does not work on Windows, I **set 'LOCAL=true**' in the command prompt before running the 'make' command.
2. I replaced occurrences of **optest'**' in the database sections of configuration files with '**op'**.


This commit reflects the necessary adjustments made to run the project successfully in my local environment.

**Comment by Sddilora** [comment]
I successfully ran the project locally.

**Comment by Sddilora** [comment]
@octoposprime/be 
@octoposprime/be-jr 
please add your comments so we can close the issue if everyone has run it successfully

**Comment by ebrarkesici** [comment]
I ran all project locally.

**Comment by Feyzanrs** [comment]
I successfully ran the project locally without any issues.

**Comment by johsquaree** [comment]
I successfully ran the project locally.

**Comment by arzuuddemir** [comment]
I successfully ran all projects locally.

**Comment by mervegonc** [comment]
I successfully ran the project locally.

**Comment by Maraza25** [comment]
I successfully ran the project locally.
